### ISSUE TITLE
Handle Cancel Query robustly

### ISSUE THREAD

**Issue by abhisheksinha89** [dbcli/mssql-cli#84]
OS: OSX 10.13.1
 
Matthews-MBP:vscode-mssql mairvine$ mssql-cli -h mairvine-pc
Username (press enter for sa): 
Password: 
Version: 0.6.0
Mail: sqlcli@microsoft.com
Home: http://github.com/dbcli/mssql-cli
master>waitfor delay '00:00:10'
^CCancelling query...
Query cancelled.
master>waitfor delay '00:00:15'
^CCancelling query...
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/mssqlcli/main.py", line 840, in <module>
    cli()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/mssqlcli/main.py", line 702, in cli
    mssqlcli.run_cli()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/mssqlcli/main.py", line 413, in run_cli
    query = self.execute_command(document.text, query)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/mssqlcli/main.py", line 338, in execute_command
    self.mssqlcliclient_query_execution)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/mssqlcli/mssqlcliclient.py", line 272, in reset_connection_and_clients
    raise e
OSError: [Errno 3] No such process

**Comment by pensivebrian** [comment]
This was fixed in the sqltoolsservice with PR https://github.com/Microsoft/sqltoolsservice/pull/498. On Windows, this no longer repros with the above steps.

**Comment by smithaitufe** [comment]
It seems this was not fixed. I am still not able to cancel running query in VSCode. I am using Ubuntu
